### ISSUE TITLE
Get the repo set up on new Pangeo Cloud

### ISSUE THREAD

**Issue by rabernat** [ocean-transport/WMT-project#1]
In order to get this set up on Pangeo Cloud, you will need to do the following

- [x] Set up SSH keys for Git: https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh
- [x] Transfer your private key to Pangeo Cloud (just drag and drop the file or edit a text file and copy and paste). In my home directory, this key lives at `.ssh/id_rsa` or something similar
- [x] For every new session, you need to type
```
$ ssh-agent bash
$ ssh-add ~/.ssh/id_rsa
```

One you complete these steps, you should be able to run
```
git clone git@github.com:ocean-transport/WMT-project.git
```

to bring in all your files.

Close this issue once you are at that point.

**Comment by rabernat** [comment]
Here is a comment.

**Comment by shanicetbailey** [comment]
> In order to get this set up on Pangeo Cloud, you will need to do the following
> 
> * [ ]  Set up SSH keys for Git: https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh
> * [ ]  Transfer your private key to Pangeo Cloud (just drag and drop the file or edit a text file and copy and paste). In my home directory, this key lives at `.ssh/id_rsa` or something similar
> * [ ]  For every new session, you need to type
> 
> ```
> $ ssh-agent bash
> $ ssh-add ~/.ssh/id_rsa
> ```
> 
> One you complete these steps, you should be able to run
> 
> ```
> git clone git@github.com:ocean-transport/WMT-project.git
> ```
> 
> to bring in all your files.
> 
> Close this issue once you are at that point.

Do I set up an ssh-agent to manage my ssh key or can I move on to the next step of transferring the key to Pangeo Cloud?

**Comment by rabernat** [comment]
No, you don't need ssh-agent to transfer the key. For that you can either drag and drop or copy / paste. But you do need it to _use_ the key in Pangeo Cloud.

**Comment by shanicetbailey** [comment]
I didn't have to copy and paste anything...I set up the key right in the terminal of pangeo cloud - is this alright? And then I just copied and pasted it to my github acct in the "SSH and Keys" section.

**Comment by rabernat** [comment]
Sounds perfect! The real test is whether it works.

**Comment by shanicetbailey** [comment]
Completed.
