### ISSUE TITLE
Get SOSE heat budget to close

### ISSUE THREAD

**Issue by rabernat** [ocean-transport/WMT-project#9]
In today's meeting, you showed that you were having some problems with the SOSE heat budget. Here are some ideas we discussed to resolve:

- Recompute the budget terms, double checking the code along the way
- Try excluding points shallower than 200m to see if the issue is related to sw penetration in the presence of shallow bathymetry

Please post any relevant figures here and I'll give you my feedback.

**Comment by shanicetbailey** [comment]
`plt.scatter(rhs_wg.isel(time=35).values.ravel(), lhs_wg.where(coords_wg.Depth<200).isel(time=35).values.ravel())`
yields this figure
![fig](https://user-images.githubusercontent.com/31974425/98584797-60d4e000-2294-11eb-9334-0112103fa533.png)

You can also see in this nb: https://nbviewer.jupyter.org/github/ocean-transport/WMT-project/blob/master/SOSE-budgets/scatter-plot-TnS-budget-SOSE.ipynb

**Comment by rabernat** [comment]
Any progress on this issue? Can I help in some way?

**Comment by shanicetbailey** [comment]
Still going through it... I'll reach out soon.
